/* Generated by Copilot 
 * Minimal URM14 Modbus RTU Master (ESP-IDF v5.5)
 * Literal translation of Arduino logic]
 *
 * ESP32-C5
 * RS485:
 *   TX  -> GPIO24
 *   RX  -> GPIO23
 *   RTS -> GPIO25
 */

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_err.h"
#include "driver/uart.h"
#include "mbcontroller.h"

/* ---------------- Configuration ---------------- */

#define TAG "URM14"

/* UART / RS485 */
#define MB_UART_PORT   UART_NUM_1
#define MB_BAUDRATE    19200

#define MB_TXD  23
#define MB_RXD  24
#define MB_RTS  25

/* URM14 Modbus */
#define SLAVE_ADDR     0x0C

/* URM14 registers (0-based for Modbus) */
#define REG_DISTANCE   5   // eDistance
#define REG_CONTROL    8   // eControl

/* Control register bits (same as Arduino) */
#define TEMP_CPT_SEL_BIT       (1 << 0)
#define TEMP_CPT_ENABLE_BIT    (1 << 1)
#define MEASURE_MODE_BIT       (1 << 2)
#define MEASURE_TRIG_BIT       (1 << 3)

/* Modbus handle */
static void *mb_handle = NULL;

/* Persistent control register (same as Arduino `cr`) */
static uint16_t cr = 0;

/* ---------------- Modbus Init ---------------- */

static void modbus_master_init(void)
{
    mb_communication_info_t comm = {
        .ser_opts.port = MB_UART_PORT,
        .ser_opts.mode = MB_RTU,
        .ser_opts.baudrate = MB_BAUDRATE,
        .ser_opts.parity = MB_PARITY_NONE,
        .ser_opts.data_bits = UART_DATA_8_BITS,
        .ser_opts.stop_bits = UART_STOP_BITS_1,
        .ser_opts.response_tout_ms = 3000
    };

    ESP_ERROR_CHECK(mbc_master_create_serial(&comm, &mb_handle));
    ESP_ERROR_CHECK(uart_set_pin(
        MB_UART_PORT,
        MB_TXD,
        MB_RXD,
        MB_RTS,
        UART_PIN_NO_CHANGE
    ));
    ESP_ERROR_CHECK(uart_set_mode(
        MB_UART_PORT,
        UART_MODE_RS485_HALF_DUPLEX
    ));
    ESP_ERROR_CHECK(mbc_master_start(mb_handle));

    ESP_LOGI(TAG, "Modbus RTU master initialized");
}

/* ---------------- Modbus helpers ---------------- */

static esp_err_t write_control(uint16_t value)
{
    mb_param_request_t req = {
        .slave_addr = SLAVE_ADDR,
        .command    = 0x06,          // Write Single Register
        .reg_start  = REG_CONTROL,
        .reg_size   = 1
    };

    return mbc_master_send_request(mb_handle, &req, &value);
}

static esp_err_t read_distance(uint16_t *value)
{
    mb_param_request_t req = {
        .slave_addr = SLAVE_ADDR,
        .command    = 0x03,          // Read Holding Registers
        .reg_start  = REG_DISTANCE,
        .reg_size   = 1
    };

    return mbc_master_send_request(mb_handle, &req, value);
}

void init_urm14(void)
{
    modbus_master_init();

    cr |= MEASURE_MODE_BIT;                 // Trigger mode
    cr &= ~TEMP_CPT_SEL_BIT;                // Internal temp
    cr &= ~TEMP_CPT_ENABLE_BIT;             // ENABLE temp compensation

    write_control(cr);                      // Same as Arduino setup()
    vTaskDelay(pdMS_TO_TICKS(100));

    // ESP_LOGI(TAG, "URM14 configured");
}

/* ---------------- Application ---------------- */

void app_main(void)
{
    uint16_t raw_distance;

    /* === Arduino setup() equivalent === */

    init_urm14();

    /* === Arduino loop() equivalent === */

    while (1) {

        cr |= MEASURE_TRIG_BIT;             // Set trigger bit
        write_control(cr);                  // Trigger ranging

        vTaskDelay(pdMS_TO_TICKS(50));     // Wait for ranging

        if (read_distance(&raw_distance) == ESP_OK) {
            float dist_mm = raw_distance / 10.0f;
            ESP_LOGI(TAG, "distance = %.1f mm (raw=%u)",
                     dist_mm, raw_distance);
        } else {
            ESP_LOGW(TAG, "Read distance failed");
        }

        vTaskDelay(pdMS_TO_TICKS(300));
    }
}